//this source code was auto-generated by tolua#, do not modify it
using System;
using LuaInterface;

public class UnityEngine_UI_CanvasUpdateRegistryWrap
{
	public static void Register(LuaState L)
	{
		L.BeginClass(typeof(UnityEngine.UI.CanvasUpdateRegistry), typeof(System.Object));
		L.RegFunction("RegisterCanvasElementForLayoutRebuild", RegisterCanvasElementForLayoutRebuild);
		L.RegFunction("TryRegisterCanvasElementForLayoutRebuild", TryRegisterCanvasElementForLayoutRebuild);
		L.RegFunction("RegisterCanvasElementForGraphicRebuild", RegisterCanvasElementForGraphicRebuild);
		L.RegFunction("TryRegisterCanvasElementForGraphicRebuild", TryRegisterCanvasElementForGraphicRebuild);
		L.RegFunction("UnRegisterCanvasElementForRebuild", UnRegisterCanvasElementForRebuild);
		L.RegFunction("IsRebuildingLayout", IsRebuildingLayout);
		L.RegFunction("IsRebuildingGraphics", IsRebuildingGraphics);
		L.RegFunction("__tostring", ToLua.op_ToString);
		L.RegVar("instance", get_instance, null);
		L.EndClass();
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int RegisterCanvasElementForLayoutRebuild(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 1);
			UnityEngine.UI.ICanvasElement arg0 = (UnityEngine.UI.ICanvasElement)ToLua.CheckObject(L, 1, typeof(UnityEngine.UI.ICanvasElement));
			UnityEngine.UI.CanvasUpdateRegistry.RegisterCanvasElementForLayoutRebuild(arg0);
			return 0;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int TryRegisterCanvasElementForLayoutRebuild(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 1);
			UnityEngine.UI.ICanvasElement arg0 = (UnityEngine.UI.ICanvasElement)ToLua.CheckObject(L, 1, typeof(UnityEngine.UI.ICanvasElement));
			bool o = UnityEngine.UI.CanvasUpdateRegistry.TryRegisterCanvasElementForLayoutRebuild(arg0);
			LuaDLL.lua_pushboolean(L, o);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int RegisterCanvasElementForGraphicRebuild(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 1);
			UnityEngine.UI.ICanvasElement arg0 = (UnityEngine.UI.ICanvasElement)ToLua.CheckObject(L, 1, typeof(UnityEngine.UI.ICanvasElement));
			UnityEngine.UI.CanvasUpdateRegistry.RegisterCanvasElementForGraphicRebuild(arg0);
			return 0;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int TryRegisterCanvasElementForGraphicRebuild(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 1);
			UnityEngine.UI.ICanvasElement arg0 = (UnityEngine.UI.ICanvasElement)ToLua.CheckObject(L, 1, typeof(UnityEngine.UI.ICanvasElement));
			bool o = UnityEngine.UI.CanvasUpdateRegistry.TryRegisterCanvasElementForGraphicRebuild(arg0);
			LuaDLL.lua_pushboolean(L, o);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int UnRegisterCanvasElementForRebuild(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 1);
			UnityEngine.UI.ICanvasElement arg0 = (UnityEngine.UI.ICanvasElement)ToLua.CheckObject(L, 1, typeof(UnityEngine.UI.ICanvasElement));
			UnityEngine.UI.CanvasUpdateRegistry.UnRegisterCanvasElementForRebuild(arg0);
			return 0;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int IsRebuildingLayout(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 0);
			bool o = UnityEngine.UI.CanvasUpdateRegistry.IsRebuildingLayout();
			LuaDLL.lua_pushboolean(L, o);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int IsRebuildingGraphics(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 0);
			bool o = UnityEngine.UI.CanvasUpdateRegistry.IsRebuildingGraphics();
			LuaDLL.lua_pushboolean(L, o);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_instance(IntPtr L)
	{
		try
		{
			ToLua.PushObject(L, UnityEngine.UI.CanvasUpdateRegistry.instance);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}
}

