//this source code was auto-generated by tolua#, do not modify it
using System;
using LuaInterface;

public class UnityEngine_UI_CanvasUpdateWrap
{
	public static void Register(LuaState L)
	{
		L.BeginEnum(typeof(UnityEngine.UI.CanvasUpdate));
		L.RegVar("Prelayout", get_Prelayout, null);
		L.RegVar("Layout", get_Layout, null);
		L.RegVar("PostLayout", get_PostLayout, null);
		L.RegVar("PreRender", get_PreRender, null);
		L.RegVar("LatePreRender", get_LatePreRender, null);
		L.RegVar("MaxUpdateValue", get_MaxUpdateValue, null);
		L.RegFunction("IntToEnum", IntToEnum);
		L.EndEnum();
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_Prelayout(IntPtr L)
	{
		ToLua.Push(L, UnityEngine.UI.CanvasUpdate.Prelayout);
		return 1;
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_Layout(IntPtr L)
	{
		ToLua.Push(L, UnityEngine.UI.CanvasUpdate.Layout);
		return 1;
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_PostLayout(IntPtr L)
	{
		ToLua.Push(L, UnityEngine.UI.CanvasUpdate.PostLayout);
		return 1;
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_PreRender(IntPtr L)
	{
		ToLua.Push(L, UnityEngine.UI.CanvasUpdate.PreRender);
		return 1;
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_LatePreRender(IntPtr L)
	{
		ToLua.Push(L, UnityEngine.UI.CanvasUpdate.LatePreRender);
		return 1;
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_MaxUpdateValue(IntPtr L)
	{
		ToLua.Push(L, UnityEngine.UI.CanvasUpdate.MaxUpdateValue);
		return 1;
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int IntToEnum(IntPtr L)
	{
		int arg0 = (int)LuaDLL.lua_tonumber(L, 1);
		UnityEngine.UI.CanvasUpdate o = (UnityEngine.UI.CanvasUpdate)arg0;
		ToLua.Push(L, o);
		return 1;
	}
}

