//this source code was auto-generated by tolua#, do not modify it
using System;
using LuaInterface;

public class UnityEngine_Rendering_BlendModeWrap
{
	public static void Register(LuaState L)
	{
		L.BeginEnum(typeof(UnityEngine.Rendering.BlendMode));
		L.RegVar("Zero", get_Zero, null);
		L.RegVar("One", get_One, null);
		L.RegVar("DstColor", get_DstColor, null);
		L.RegVar("SrcColor", get_SrcColor, null);
		L.RegVar("OneMinusDstColor", get_OneMinusDstColor, null);
		L.RegVar("SrcAlpha", get_SrcAlpha, null);
		L.RegVar("OneMinusSrcColor", get_OneMinusSrcColor, null);
		L.RegVar("DstAlpha", get_DstAlpha, null);
		L.RegVar("OneMinusDstAlpha", get_OneMinusDstAlpha, null);
		L.RegVar("SrcAlphaSaturate", get_SrcAlphaSaturate, null);
		L.RegVar("OneMinusSrcAlpha", get_OneMinusSrcAlpha, null);
		L.RegFunction("IntToEnum", IntToEnum);
		L.EndEnum();
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_Zero(IntPtr L)
	{
		ToLua.Push(L, UnityEngine.Rendering.BlendMode.Zero);
		return 1;
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_One(IntPtr L)
	{
		ToLua.Push(L, UnityEngine.Rendering.BlendMode.One);
		return 1;
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_DstColor(IntPtr L)
	{
		ToLua.Push(L, UnityEngine.Rendering.BlendMode.DstColor);
		return 1;
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_SrcColor(IntPtr L)
	{
		ToLua.Push(L, UnityEngine.Rendering.BlendMode.SrcColor);
		return 1;
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_OneMinusDstColor(IntPtr L)
	{
		ToLua.Push(L, UnityEngine.Rendering.BlendMode.OneMinusDstColor);
		return 1;
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_SrcAlpha(IntPtr L)
	{
		ToLua.Push(L, UnityEngine.Rendering.BlendMode.SrcAlpha);
		return 1;
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_OneMinusSrcColor(IntPtr L)
	{
		ToLua.Push(L, UnityEngine.Rendering.BlendMode.OneMinusSrcColor);
		return 1;
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_DstAlpha(IntPtr L)
	{
		ToLua.Push(L, UnityEngine.Rendering.BlendMode.DstAlpha);
		return 1;
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_OneMinusDstAlpha(IntPtr L)
	{
		ToLua.Push(L, UnityEngine.Rendering.BlendMode.OneMinusDstAlpha);
		return 1;
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_SrcAlphaSaturate(IntPtr L)
	{
		ToLua.Push(L, UnityEngine.Rendering.BlendMode.SrcAlphaSaturate);
		return 1;
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_OneMinusSrcAlpha(IntPtr L)
	{
		ToLua.Push(L, UnityEngine.Rendering.BlendMode.OneMinusSrcAlpha);
		return 1;
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int IntToEnum(IntPtr L)
	{
		int arg0 = (int)LuaDLL.lua_tonumber(L, 1);
		UnityEngine.Rendering.BlendMode o = (UnityEngine.Rendering.BlendMode)arg0;
		ToLua.Push(L, o);
		return 1;
	}
}

