//this source code was auto-generated by tolua#, do not modify it
using System;
using LuaInterface;

public class UnityEngine_Rendering_OpaqueSortModeWrap
{
	public static void Register(LuaState L)
	{
		L.BeginEnum(typeof(UnityEngine.Rendering.OpaqueSortMode));
		L.RegVar("Default", get_Default, null);
		L.RegVar("FrontToBack", get_FrontToBack, null);
		L.RegVar("NoDistanceSort", get_NoDistanceSort, null);
		L.RegFunction("IntToEnum", IntToEnum);
		L.EndEnum();
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_Default(IntPtr L)
	{
		ToLua.Push(L, UnityEngine.Rendering.OpaqueSortMode.Default);
		return 1;
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_FrontToBack(IntPtr L)
	{
		ToLua.Push(L, UnityEngine.Rendering.OpaqueSortMode.FrontToBack);
		return 1;
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_NoDistanceSort(IntPtr L)
	{
		ToLua.Push(L, UnityEngine.Rendering.OpaqueSortMode.NoDistanceSort);
		return 1;
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int IntToEnum(IntPtr L)
	{
		int arg0 = (int)LuaDLL.lua_tonumber(L, 1);
		UnityEngine.Rendering.OpaqueSortMode o = (UnityEngine.Rendering.OpaqueSortMode)arg0;
		ToLua.Push(L, o);
		return 1;
	}
}

