//this source code was auto-generated by tolua#, do not modify it
using System;
using LuaInterface;

public class UnityEngine_ContactPoint2DWrap
{
	public static void Register(LuaState L)
	{
		L.BeginClass(typeof(UnityEngine.ContactPoint2D), null);
		L.RegFunction("New", _CreateUnityEngine_ContactPoint2D);
		L.RegFunction("__tostring", ToLua.op_ToString);
		L.RegVar("point", get_point, null);
		L.RegVar("normal", get_normal, null);
		L.RegVar("collider", get_collider, null);
		L.RegVar("otherCollider", get_otherCollider, null);
		L.EndClass();
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int _CreateUnityEngine_ContactPoint2D(IntPtr L)
	{
		UnityEngine.ContactPoint2D obj = new UnityEngine.ContactPoint2D();
		ToLua.PushValue(L, obj);
		return 1;
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_point(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			UnityEngine.ContactPoint2D obj = (UnityEngine.ContactPoint2D)o;
			UnityEngine.Vector2 ret = obj.point;
			ToLua.Push(L, ret);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o == null ? "attempt to index point on a nil value" : e.Message);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_normal(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			UnityEngine.ContactPoint2D obj = (UnityEngine.ContactPoint2D)o;
			UnityEngine.Vector2 ret = obj.normal;
			ToLua.Push(L, ret);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o == null ? "attempt to index normal on a nil value" : e.Message);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_collider(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			UnityEngine.ContactPoint2D obj = (UnityEngine.ContactPoint2D)o;
			UnityEngine.Collider2D ret = obj.collider;
			ToLua.Push(L, ret);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o == null ? "attempt to index collider on a nil value" : e.Message);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_otherCollider(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			UnityEngine.ContactPoint2D obj = (UnityEngine.ContactPoint2D)o;
			UnityEngine.Collider2D ret = obj.otherCollider;
			ToLua.Push(L, ret);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o == null ? "attempt to index otherCollider on a nil value" : e.Message);
		}
	}
}

