//this source code was auto-generated by tolua#, do not modify it
using System;
using LuaInterface;

public class UnityEngine_RigidbodySleepMode2DWrap
{
	public static void Register(LuaState L)
	{
		L.BeginEnum(typeof(UnityEngine.RigidbodySleepMode2D));
		L.RegVar("NeverSleep", get_NeverSleep, null);
		L.RegVar("StartAwake", get_StartAwake, null);
		L.RegVar("StartAsleep", get_StartAsleep, null);
		L.RegFunction("IntToEnum", IntToEnum);
		L.EndEnum();
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_NeverSleep(IntPtr L)
	{
		ToLua.Push(L, UnityEngine.RigidbodySleepMode2D.NeverSleep);
		return 1;
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_StartAwake(IntPtr L)
	{
		ToLua.Push(L, UnityEngine.RigidbodySleepMode2D.StartAwake);
		return 1;
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_StartAsleep(IntPtr L)
	{
		ToLua.Push(L, UnityEngine.RigidbodySleepMode2D.StartAsleep);
		return 1;
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int IntToEnum(IntPtr L)
	{
		int arg0 = (int)LuaDLL.lua_tonumber(L, 1);
		UnityEngine.RigidbodySleepMode2D o = (UnityEngine.RigidbodySleepMode2D)arg0;
		ToLua.Push(L, o);
		return 1;
	}
}

