//this source code was auto-generated by tolua#, do not modify it
using System;
using LuaInterface;

public class UnityEngine_Rendering_AmbientModeWrap
{
	public static void Register(LuaState L)
	{
		L.BeginEnum(typeof(UnityEngine.Rendering.AmbientMode));
		L.RegVar("Skybox", get_Skybox, null);
		L.RegVar("Trilight", get_Trilight, null);
		L.RegVar("Flat", get_Flat, null);
		L.RegVar("Custom", get_Custom, null);
		L.RegFunction("IntToEnum", IntToEnum);
		L.EndEnum();
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_Skybox(IntPtr L)
	{
		ToLua.Push(L, UnityEngine.Rendering.AmbientMode.Skybox);
		return 1;
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_Trilight(IntPtr L)
	{
		ToLua.Push(L, UnityEngine.Rendering.AmbientMode.Trilight);
		return 1;
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_Flat(IntPtr L)
	{
		ToLua.Push(L, UnityEngine.Rendering.AmbientMode.Flat);
		return 1;
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_Custom(IntPtr L)
	{
		ToLua.Push(L, UnityEngine.Rendering.AmbientMode.Custom);
		return 1;
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int IntToEnum(IntPtr L)
	{
		int arg0 = (int)LuaDLL.lua_tonumber(L, 1);
		UnityEngine.Rendering.AmbientMode o = (UnityEngine.Rendering.AmbientMode)arg0;
		ToLua.Push(L, o);
		return 1;
	}
}

