//this source code was auto-generated by tolua#, do not modify it
using System;
using LuaInterface;

public class UnityEngine_Rendering_CullModeWrap
{
	public static void Register(LuaState L)
	{
		L.BeginEnum(typeof(UnityEngine.Rendering.CullMode));
		L.RegVar("Off", get_Off, null);
		L.RegVar("Front", get_Front, null);
		L.RegVar("Back", get_Back, null);
		L.RegFunction("IntToEnum", IntToEnum);
		L.EndEnum();
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_Off(IntPtr L)
	{
		ToLua.Push(L, UnityEngine.Rendering.CullMode.Off);
		return 1;
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_Front(IntPtr L)
	{
		ToLua.Push(L, UnityEngine.Rendering.CullMode.Front);
		return 1;
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_Back(IntPtr L)
	{
		ToLua.Push(L, UnityEngine.Rendering.CullMode.Back);
		return 1;
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int IntToEnum(IntPtr L)
	{
		int arg0 = (int)LuaDLL.lua_tonumber(L, 1);
		UnityEngine.Rendering.CullMode o = (UnityEngine.Rendering.CullMode)arg0;
		ToLua.Push(L, o);
		return 1;
	}
}

