//this source code was auto-generated by tolua#, do not modify it
using System;
using LuaInterface;

public class UnityEngine_ParticleSystemAnimationTypeWrap
{
	public static void Register(LuaState L)
	{
		L.BeginEnum(typeof(UnityEngine.ParticleSystemAnimationType));
		L.RegVar("WholeSheet", get_WholeSheet, null);
		L.RegVar("SingleRow", get_SingleRow, null);
		L.RegFunction("IntToEnum", IntToEnum);
		L.EndEnum();
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_WholeSheet(IntPtr L)
	{
		ToLua.Push(L, UnityEngine.ParticleSystemAnimationType.WholeSheet);
		return 1;
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_SingleRow(IntPtr L)
	{
		ToLua.Push(L, UnityEngine.ParticleSystemAnimationType.SingleRow);
		return 1;
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int IntToEnum(IntPtr L)
	{
		int arg0 = (int)LuaDLL.lua_tonumber(L, 1);
		UnityEngine.ParticleSystemAnimationType o = (UnityEngine.ParticleSystemAnimationType)arg0;
		ToLua.Push(L, o);
		return 1;
	}
}

