//this source code was auto-generated by tolua#, do not modify it
using System;
using LuaInterface;

public class UnityEngine_ShadowProjectionWrap
{
	public static void Register(LuaState L)
	{
		L.BeginEnum(typeof(UnityEngine.ShadowProjection));
		L.RegVar("CloseFit", get_CloseFit, null);
		L.RegVar("StableFit", get_StableFit, null);
		L.RegFunction("IntToEnum", IntToEnum);
		L.EndEnum();
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_CloseFit(IntPtr L)
	{
		ToLua.Push(L, UnityEngine.ShadowProjection.CloseFit);
		return 1;
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_StableFit(IntPtr L)
	{
		ToLua.Push(L, UnityEngine.ShadowProjection.StableFit);
		return 1;
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int IntToEnum(IntPtr L)
	{
		int arg0 = (int)LuaDLL.lua_tonumber(L, 1);
		UnityEngine.ShadowProjection o = (UnityEngine.ShadowProjection)arg0;
		ToLua.Push(L, o);
		return 1;
	}
}

