//this source code was auto-generated by tolua#, do not modify it
using System;
using LuaInterface;

public class UnityEngine_Rendering_BuiltinShaderModeWrap
{
	public static void Register(LuaState L)
	{
		L.BeginEnum(typeof(UnityEngine.Rendering.BuiltinShaderMode));
		L.RegVar("Disabled", get_Disabled, null);
		L.RegVar("UseBuiltin", get_UseBuiltin, null);
		L.RegVar("UseCustom", get_UseCustom, null);
		L.RegFunction("IntToEnum", IntToEnum);
		L.EndEnum();
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_Disabled(IntPtr L)
	{
		ToLua.Push(L, UnityEngine.Rendering.BuiltinShaderMode.Disabled);
		return 1;
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_UseBuiltin(IntPtr L)
	{
		ToLua.Push(L, UnityEngine.Rendering.BuiltinShaderMode.UseBuiltin);
		return 1;
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_UseCustom(IntPtr L)
	{
		ToLua.Push(L, UnityEngine.Rendering.BuiltinShaderMode.UseCustom);
		return 1;
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int IntToEnum(IntPtr L)
	{
		int arg0 = (int)LuaDLL.lua_tonumber(L, 1);
		UnityEngine.Rendering.BuiltinShaderMode o = (UnityEngine.Rendering.BuiltinShaderMode)arg0;
		ToLua.Push(L, o);
		return 1;
	}
}

