//this source code was auto-generated by tolua#, do not modify it
using System;
using LuaInterface;

public class UnityEngine_ParticlePhysicsExtensionsWrap
{
	public static void Register(LuaState L)
	{
		L.BeginStaticLibs("ParticlePhysicsExtensions");
		L.RegFunction("GetSafeCollisionEventSize", GetSafeCollisionEventSize);
		L.RegFunction("GetCollisionEvents", GetCollisionEvents);
		L.EndStaticLibs();
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int GetSafeCollisionEventSize(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 1);
			UnityEngine.ParticleSystem arg0 = (UnityEngine.ParticleSystem)ToLua.CheckUnityObject(L, 1, typeof(UnityEngine.ParticleSystem));
			int o = UnityEngine.ParticlePhysicsExtensions.GetSafeCollisionEventSize(arg0);
			LuaDLL.lua_pushinteger(L, o);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int GetCollisionEvents(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 3);
			UnityEngine.ParticleSystem arg0 = (UnityEngine.ParticleSystem)ToLua.CheckUnityObject(L, 1, typeof(UnityEngine.ParticleSystem));
			UnityEngine.GameObject arg1 = (UnityEngine.GameObject)ToLua.CheckUnityObject(L, 2, typeof(UnityEngine.GameObject));
			UnityEngine.ParticleCollisionEvent[] arg2 = ToLua.CheckObjectArray<UnityEngine.ParticleCollisionEvent>(L, 3);
			int o = UnityEngine.ParticlePhysicsExtensions.GetCollisionEvents(arg0, arg1, arg2);
			LuaDLL.lua_pushinteger(L, o);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}
}

