//this source code was auto-generated by tolua#, do not modify it
using System;
using LuaInterface;

public class UnityEngine_RenderTextureReadWriteWrap
{
	public static void Register(LuaState L)
	{
		L.BeginEnum(typeof(UnityEngine.RenderTextureReadWrite));
		L.RegVar("Default", get_Default, null);
		L.RegVar("Linear", get_Linear, null);
		L.RegVar("sRGB", get_sRGB, null);
		L.RegFunction("IntToEnum", IntToEnum);
		L.EndEnum();
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_Default(IntPtr L)
	{
		ToLua.Push(L, UnityEngine.RenderTextureReadWrite.Default);
		return 1;
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_Linear(IntPtr L)
	{
		ToLua.Push(L, UnityEngine.RenderTextureReadWrite.Linear);
		return 1;
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_sRGB(IntPtr L)
	{
		ToLua.Push(L, UnityEngine.RenderTextureReadWrite.sRGB);
		return 1;
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int IntToEnum(IntPtr L)
	{
		int arg0 = (int)LuaDLL.lua_tonumber(L, 1);
		UnityEngine.RenderTextureReadWrite o = (UnityEngine.RenderTextureReadWrite)arg0;
		ToLua.Push(L, o);
		return 1;
	}
}

