//this source code was auto-generated by tolua#, do not modify it
using System;
using LuaInterface;

public class UnityEngine_GUILayout_ScrollViewScopeWrap
{
	public static void Register(LuaState L)
	{
		L.BeginClass(typeof(UnityEngine.GUILayout.ScrollViewScope), typeof(UnityEngine.GUI.Scope));
		L.RegFunction("New", _CreateUnityEngine_GUILayout_ScrollViewScope);
		L.RegFunction("__tostring", ToLua.op_ToString);
		L.RegVar("scrollPosition", get_scrollPosition, null);
		L.RegVar("handleScrollWheel", get_handleScrollWheel, set_handleScrollWheel);
		L.EndClass();
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int _CreateUnityEngine_GUILayout_ScrollViewScope(IntPtr L)
	{
		try
		{
			int count = LuaDLL.lua_gettop(L);

			if (TypeChecker.CheckTypes(L, 1, typeof(UnityEngine.Vector2), typeof(bool), typeof(bool), typeof(UnityEngine.GUIStyle), typeof(UnityEngine.GUIStyle), typeof(UnityEngine.GUIStyle)) && TypeChecker.CheckParamsType(L, typeof(UnityEngine.GUILayoutOption), 7, count - 6))
			{
				UnityEngine.Vector2 arg0 = ToLua.ToVector2(L, 1);
				bool arg1 = LuaDLL.luaL_checkboolean(L, 2);
				bool arg2 = LuaDLL.luaL_checkboolean(L, 3);
				UnityEngine.GUIStyle arg3 = (UnityEngine.GUIStyle)ToLua.CheckObject(L, 4, typeof(UnityEngine.GUIStyle));
				UnityEngine.GUIStyle arg4 = (UnityEngine.GUIStyle)ToLua.CheckObject(L, 5, typeof(UnityEngine.GUIStyle));
				UnityEngine.GUIStyle arg5 = (UnityEngine.GUIStyle)ToLua.CheckObject(L, 6, typeof(UnityEngine.GUIStyle));
				UnityEngine.GUILayoutOption[] arg6 = ToLua.CheckParamsObject<UnityEngine.GUILayoutOption>(L, 7, count - 6);
				UnityEngine.GUILayout.ScrollViewScope obj = new UnityEngine.GUILayout.ScrollViewScope(arg0, arg1, arg2, arg3, arg4, arg5, arg6);
				ToLua.PushObject(L, obj);
				return 1;
			}
			else if (TypeChecker.CheckTypes(L, 1, typeof(UnityEngine.Vector2), typeof(bool), typeof(bool), typeof(UnityEngine.GUIStyle), typeof(UnityEngine.GUIStyle)) && TypeChecker.CheckParamsType(L, typeof(UnityEngine.GUILayoutOption), 6, count - 5))
			{
				UnityEngine.Vector2 arg0 = ToLua.ToVector2(L, 1);
				bool arg1 = LuaDLL.luaL_checkboolean(L, 2);
				bool arg2 = LuaDLL.luaL_checkboolean(L, 3);
				UnityEngine.GUIStyle arg3 = (UnityEngine.GUIStyle)ToLua.CheckObject(L, 4, typeof(UnityEngine.GUIStyle));
				UnityEngine.GUIStyle arg4 = (UnityEngine.GUIStyle)ToLua.CheckObject(L, 5, typeof(UnityEngine.GUIStyle));
				UnityEngine.GUILayoutOption[] arg5 = ToLua.CheckParamsObject<UnityEngine.GUILayoutOption>(L, 6, count - 5);
				UnityEngine.GUILayout.ScrollViewScope obj = new UnityEngine.GUILayout.ScrollViewScope(arg0, arg1, arg2, arg3, arg4, arg5);
				ToLua.PushObject(L, obj);
				return 1;
			}
			else if (TypeChecker.CheckTypes(L, 1, typeof(UnityEngine.Vector2), typeof(UnityEngine.GUIStyle), typeof(UnityEngine.GUIStyle)) && TypeChecker.CheckParamsType(L, typeof(UnityEngine.GUILayoutOption), 4, count - 3))
			{
				UnityEngine.Vector2 arg0 = ToLua.ToVector2(L, 1);
				UnityEngine.GUIStyle arg1 = (UnityEngine.GUIStyle)ToLua.CheckObject(L, 2, typeof(UnityEngine.GUIStyle));
				UnityEngine.GUIStyle arg2 = (UnityEngine.GUIStyle)ToLua.CheckObject(L, 3, typeof(UnityEngine.GUIStyle));
				UnityEngine.GUILayoutOption[] arg3 = ToLua.CheckParamsObject<UnityEngine.GUILayoutOption>(L, 4, count - 3);
				UnityEngine.GUILayout.ScrollViewScope obj = new UnityEngine.GUILayout.ScrollViewScope(arg0, arg1, arg2, arg3);
				ToLua.PushObject(L, obj);
				return 1;
			}
			else if (TypeChecker.CheckTypes(L, 1, typeof(UnityEngine.Vector2), typeof(bool), typeof(bool)) && TypeChecker.CheckParamsType(L, typeof(UnityEngine.GUILayoutOption), 4, count - 3))
			{
				UnityEngine.Vector2 arg0 = ToLua.ToVector2(L, 1);
				bool arg1 = LuaDLL.luaL_checkboolean(L, 2);
				bool arg2 = LuaDLL.luaL_checkboolean(L, 3);
				UnityEngine.GUILayoutOption[] arg3 = ToLua.CheckParamsObject<UnityEngine.GUILayoutOption>(L, 4, count - 3);
				UnityEngine.GUILayout.ScrollViewScope obj = new UnityEngine.GUILayout.ScrollViewScope(arg0, arg1, arg2, arg3);
				ToLua.PushObject(L, obj);
				return 1;
			}
			else if (TypeChecker.CheckTypes(L, 1, typeof(UnityEngine.Vector2), typeof(UnityEngine.GUIStyle)) && TypeChecker.CheckParamsType(L, typeof(UnityEngine.GUILayoutOption), 3, count - 2))
			{
				UnityEngine.Vector2 arg0 = ToLua.ToVector2(L, 1);
				UnityEngine.GUIStyle arg1 = (UnityEngine.GUIStyle)ToLua.CheckObject(L, 2, typeof(UnityEngine.GUIStyle));
				UnityEngine.GUILayoutOption[] arg2 = ToLua.CheckParamsObject<UnityEngine.GUILayoutOption>(L, 3, count - 2);
				UnityEngine.GUILayout.ScrollViewScope obj = new UnityEngine.GUILayout.ScrollViewScope(arg0, arg1, arg2);
				ToLua.PushObject(L, obj);
				return 1;
			}
			else if (TypeChecker.CheckTypes(L, 1, typeof(UnityEngine.Vector2)) && TypeChecker.CheckParamsType(L, typeof(UnityEngine.GUILayoutOption), 2, count - 1))
			{
				UnityEngine.Vector2 arg0 = ToLua.ToVector2(L, 1);
				UnityEngine.GUILayoutOption[] arg1 = ToLua.CheckParamsObject<UnityEngine.GUILayoutOption>(L, 2, count - 1);
				UnityEngine.GUILayout.ScrollViewScope obj = new UnityEngine.GUILayout.ScrollViewScope(arg0, arg1);
				ToLua.PushObject(L, obj);
				return 1;
			}
			else
			{
				return LuaDLL.luaL_throw(L, "invalid arguments to ctor method: UnityEngine.GUILayout.ScrollViewScope.New");
			}
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_scrollPosition(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			UnityEngine.GUILayout.ScrollViewScope obj = (UnityEngine.GUILayout.ScrollViewScope)o;
			UnityEngine.Vector2 ret = obj.scrollPosition;
			ToLua.Push(L, ret);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o == null ? "attempt to index scrollPosition on a nil value" : e.Message);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_handleScrollWheel(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			UnityEngine.GUILayout.ScrollViewScope obj = (UnityEngine.GUILayout.ScrollViewScope)o;
			bool ret = obj.handleScrollWheel;
			LuaDLL.lua_pushboolean(L, ret);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o == null ? "attempt to index handleScrollWheel on a nil value" : e.Message);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int set_handleScrollWheel(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			UnityEngine.GUILayout.ScrollViewScope obj = (UnityEngine.GUILayout.ScrollViewScope)o;
			bool arg0 = LuaDLL.luaL_checkboolean(L, 2);
			obj.handleScrollWheel = arg0;
			return 0;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o == null ? "attempt to index handleScrollWheel on a nil value" : e.Message);
		}
	}
}

