//this source code was auto-generated by tolua#, do not modify it
using System;
using LuaInterface;

public class UnityEngine_Networking_Match_CreateDedicatedMatchRequestWrap
{
	public static void Register(LuaState L)
	{
		L.BeginClass(typeof(UnityEngine.Networking.Match.CreateDedicatedMatchRequest), typeof(UnityEngine.Networking.Match.Request));
		L.RegFunction("IsValid", IsValid);
		L.RegFunction("New", _CreateUnityEngine_Networking_Match_CreateDedicatedMatchRequest);
		L.RegFunction("__tostring", ToLua.op_ToString);
		L.RegVar("name", get_name, set_name);
		L.RegVar("size", get_size, set_size);
		L.RegVar("advertise", get_advertise, set_advertise);
		L.RegVar("password", get_password, set_password);
		L.RegVar("publicAddress", get_publicAddress, set_publicAddress);
		L.RegVar("privateAddress", get_privateAddress, set_privateAddress);
		L.RegVar("eloScore", get_eloScore, set_eloScore);
		L.RegVar("matchAttributes", get_matchAttributes, set_matchAttributes);
		L.EndClass();
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int _CreateUnityEngine_Networking_Match_CreateDedicatedMatchRequest(IntPtr L)
	{
		try
		{
			int count = LuaDLL.lua_gettop(L);

			if (count == 0)
			{
				UnityEngine.Networking.Match.CreateDedicatedMatchRequest obj = new UnityEngine.Networking.Match.CreateDedicatedMatchRequest();
				ToLua.PushObject(L, obj);
				return 1;
			}
			else
			{
				return LuaDLL.luaL_throw(L, "invalid arguments to ctor method: UnityEngine.Networking.Match.CreateDedicatedMatchRequest.New");
			}
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int IsValid(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 1);
			UnityEngine.Networking.Match.CreateDedicatedMatchRequest obj = (UnityEngine.Networking.Match.CreateDedicatedMatchRequest)ToLua.CheckObject(L, 1, typeof(UnityEngine.Networking.Match.CreateDedicatedMatchRequest));
			bool o = obj.IsValid();
			LuaDLL.lua_pushboolean(L, o);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_name(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			UnityEngine.Networking.Match.CreateDedicatedMatchRequest obj = (UnityEngine.Networking.Match.CreateDedicatedMatchRequest)o;
			string ret = obj.name;
			LuaDLL.lua_pushstring(L, ret);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o == null ? "attempt to index name on a nil value" : e.Message);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_size(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			UnityEngine.Networking.Match.CreateDedicatedMatchRequest obj = (UnityEngine.Networking.Match.CreateDedicatedMatchRequest)o;
			uint ret = obj.size;
			LuaDLL.lua_pushnumber(L, ret);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o == null ? "attempt to index size on a nil value" : e.Message);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_advertise(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			UnityEngine.Networking.Match.CreateDedicatedMatchRequest obj = (UnityEngine.Networking.Match.CreateDedicatedMatchRequest)o;
			bool ret = obj.advertise;
			LuaDLL.lua_pushboolean(L, ret);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o == null ? "attempt to index advertise on a nil value" : e.Message);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_password(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			UnityEngine.Networking.Match.CreateDedicatedMatchRequest obj = (UnityEngine.Networking.Match.CreateDedicatedMatchRequest)o;
			string ret = obj.password;
			LuaDLL.lua_pushstring(L, ret);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o == null ? "attempt to index password on a nil value" : e.Message);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_publicAddress(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			UnityEngine.Networking.Match.CreateDedicatedMatchRequest obj = (UnityEngine.Networking.Match.CreateDedicatedMatchRequest)o;
			string ret = obj.publicAddress;
			LuaDLL.lua_pushstring(L, ret);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o == null ? "attempt to index publicAddress on a nil value" : e.Message);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_privateAddress(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			UnityEngine.Networking.Match.CreateDedicatedMatchRequest obj = (UnityEngine.Networking.Match.CreateDedicatedMatchRequest)o;
			string ret = obj.privateAddress;
			LuaDLL.lua_pushstring(L, ret);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o == null ? "attempt to index privateAddress on a nil value" : e.Message);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_eloScore(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			UnityEngine.Networking.Match.CreateDedicatedMatchRequest obj = (UnityEngine.Networking.Match.CreateDedicatedMatchRequest)o;
			int ret = obj.eloScore;
			LuaDLL.lua_pushinteger(L, ret);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o == null ? "attempt to index eloScore on a nil value" : e.Message);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_matchAttributes(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			UnityEngine.Networking.Match.CreateDedicatedMatchRequest obj = (UnityEngine.Networking.Match.CreateDedicatedMatchRequest)o;
			System.Collections.Generic.Dictionary<string,long> ret = obj.matchAttributes;
			ToLua.PushObject(L, ret);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o == null ? "attempt to index matchAttributes on a nil value" : e.Message);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int set_name(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			UnityEngine.Networking.Match.CreateDedicatedMatchRequest obj = (UnityEngine.Networking.Match.CreateDedicatedMatchRequest)o;
			string arg0 = ToLua.CheckString(L, 2);
			obj.name = arg0;
			return 0;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o == null ? "attempt to index name on a nil value" : e.Message);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int set_size(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			UnityEngine.Networking.Match.CreateDedicatedMatchRequest obj = (UnityEngine.Networking.Match.CreateDedicatedMatchRequest)o;
			uint arg0 = (uint)LuaDLL.luaL_checknumber(L, 2);
			obj.size = arg0;
			return 0;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o == null ? "attempt to index size on a nil value" : e.Message);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int set_advertise(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			UnityEngine.Networking.Match.CreateDedicatedMatchRequest obj = (UnityEngine.Networking.Match.CreateDedicatedMatchRequest)o;
			bool arg0 = LuaDLL.luaL_checkboolean(L, 2);
			obj.advertise = arg0;
			return 0;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o == null ? "attempt to index advertise on a nil value" : e.Message);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int set_password(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			UnityEngine.Networking.Match.CreateDedicatedMatchRequest obj = (UnityEngine.Networking.Match.CreateDedicatedMatchRequest)o;
			string arg0 = ToLua.CheckString(L, 2);
			obj.password = arg0;
			return 0;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o == null ? "attempt to index password on a nil value" : e.Message);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int set_publicAddress(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			UnityEngine.Networking.Match.CreateDedicatedMatchRequest obj = (UnityEngine.Networking.Match.CreateDedicatedMatchRequest)o;
			string arg0 = ToLua.CheckString(L, 2);
			obj.publicAddress = arg0;
			return 0;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o == null ? "attempt to index publicAddress on a nil value" : e.Message);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int set_privateAddress(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			UnityEngine.Networking.Match.CreateDedicatedMatchRequest obj = (UnityEngine.Networking.Match.CreateDedicatedMatchRequest)o;
			string arg0 = ToLua.CheckString(L, 2);
			obj.privateAddress = arg0;
			return 0;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o == null ? "attempt to index privateAddress on a nil value" : e.Message);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int set_eloScore(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			UnityEngine.Networking.Match.CreateDedicatedMatchRequest obj = (UnityEngine.Networking.Match.CreateDedicatedMatchRequest)o;
			int arg0 = (int)LuaDLL.luaL_checknumber(L, 2);
			obj.eloScore = arg0;
			return 0;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o == null ? "attempt to index eloScore on a nil value" : e.Message);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int set_matchAttributes(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			UnityEngine.Networking.Match.CreateDedicatedMatchRequest obj = (UnityEngine.Networking.Match.CreateDedicatedMatchRequest)o;
			System.Collections.Generic.Dictionary<string,long> arg0 = (System.Collections.Generic.Dictionary<string,long>)ToLua.CheckObject(L, 2, typeof(System.Collections.Generic.Dictionary<string,long>));
			obj.matchAttributes = arg0;
			return 0;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o == null ? "attempt to index matchAttributes on a nil value" : e.Message);
		}
	}
}

