//this source code was auto-generated by tolua#, do not modify it
using System;
using LuaInterface;

public class UnityEngine_ParticleSystemSimulationSpaceWrap
{
	public static void Register(LuaState L)
	{
		L.BeginEnum(typeof(UnityEngine.ParticleSystemSimulationSpace));
		L.RegVar("Local", get_Local, null);
		L.RegVar("World", get_World, null);
		L.RegFunction("IntToEnum", IntToEnum);
		L.EndEnum();
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_Local(IntPtr L)
	{
		ToLua.Push(L, UnityEngine.ParticleSystemSimulationSpace.Local);
		return 1;
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_World(IntPtr L)
	{
		ToLua.Push(L, UnityEngine.ParticleSystemSimulationSpace.World);
		return 1;
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int IntToEnum(IntPtr L)
	{
		int arg0 = (int)LuaDLL.lua_tonumber(L, 1);
		UnityEngine.ParticleSystemSimulationSpace o = (UnityEngine.ParticleSystemSimulationSpace)arg0;
		ToLua.Push(L, o);
		return 1;
	}
}

