//this source code was auto-generated by tolua#, do not modify it
using System;
using LuaInterface;

public class UnityEngine_NetworkDisconnectionWrap
{
	public static void Register(LuaState L)
	{
		L.BeginEnum(typeof(UnityEngine.NetworkDisconnection));
		L.RegVar("LostConnection", get_LostConnection, null);
		L.RegVar("Disconnected", get_Disconnected, null);
		L.RegFunction("IntToEnum", IntToEnum);
		L.EndEnum();
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_LostConnection(IntPtr L)
	{
		ToLua.Push(L, UnityEngine.NetworkDisconnection.LostConnection);
		return 1;
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_Disconnected(IntPtr L)
	{
		ToLua.Push(L, UnityEngine.NetworkDisconnection.Disconnected);
		return 1;
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int IntToEnum(IntPtr L)
	{
		int arg0 = (int)LuaDLL.lua_tonumber(L, 1);
		UnityEngine.NetworkDisconnection o = (UnityEngine.NetworkDisconnection)arg0;
		ToLua.Push(L, o);
		return 1;
	}
}

