//this source code was auto-generated by tolua#, do not modify it
using System;
using LuaInterface;

public class UnityEngine_Networking_Match_StopDedicatedMatchRequestWrap
{
	public static void Register(LuaState L)
	{
		L.BeginClass(typeof(UnityEngine.Networking.Match.StopDedicatedMatchRequest), typeof(UnityEngine.Networking.Match.Request));
		L.RegFunction("New", _CreateUnityEngine_Networking_Match_StopDedicatedMatchRequest);
		L.RegFunction("__tostring", ToLua.op_ToString);
		L.RegVar("networkId", get_networkId, set_networkId);
		L.EndClass();
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int _CreateUnityEngine_Networking_Match_StopDedicatedMatchRequest(IntPtr L)
	{
		try
		{
			int count = LuaDLL.lua_gettop(L);

			if (count == 0)
			{
				UnityEngine.Networking.Match.StopDedicatedMatchRequest obj = new UnityEngine.Networking.Match.StopDedicatedMatchRequest();
				ToLua.PushObject(L, obj);
				return 1;
			}
			else
			{
				return LuaDLL.luaL_throw(L, "invalid arguments to ctor method: UnityEngine.Networking.Match.StopDedicatedMatchRequest.New");
			}
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_networkId(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			UnityEngine.Networking.Match.StopDedicatedMatchRequest obj = (UnityEngine.Networking.Match.StopDedicatedMatchRequest)o;
			UnityEngine.Networking.Types.NetworkID ret = obj.networkId;
			ToLua.Push(L, ret);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o == null ? "attempt to index networkId on a nil value" : e.Message);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int set_networkId(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			UnityEngine.Networking.Match.StopDedicatedMatchRequest obj = (UnityEngine.Networking.Match.StopDedicatedMatchRequest)o;
			UnityEngine.Networking.Types.NetworkID arg0 = (UnityEngine.Networking.Types.NetworkID)ToLua.CheckObject(L, 2, typeof(UnityEngine.Networking.Types.NetworkID));
			obj.networkId = arg0;
			return 0;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o == null ? "attempt to index networkId on a nil value" : e.Message);
		}
	}
}

