//this source code was auto-generated by tolua#, do not modify it
using System;
using LuaInterface;

public class UnityEngine_ScaleModeWrap
{
	public static void Register(LuaState L)
	{
		L.BeginEnum(typeof(UnityEngine.ScaleMode));
		L.RegVar("StretchToFill", get_StretchToFill, null);
		L.RegVar("ScaleAndCrop", get_ScaleAndCrop, null);
		L.RegVar("ScaleToFit", get_ScaleToFit, null);
		L.RegFunction("IntToEnum", IntToEnum);
		L.EndEnum();
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_StretchToFill(IntPtr L)
	{
		ToLua.Push(L, UnityEngine.ScaleMode.StretchToFill);
		return 1;
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_ScaleAndCrop(IntPtr L)
	{
		ToLua.Push(L, UnityEngine.ScaleMode.ScaleAndCrop);
		return 1;
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_ScaleToFit(IntPtr L)
	{
		ToLua.Push(L, UnityEngine.ScaleMode.ScaleToFit);
		return 1;
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int IntToEnum(IntPtr L)
	{
		int arg0 = (int)LuaDLL.lua_tonumber(L, 1);
		UnityEngine.ScaleMode o = (UnityEngine.ScaleMode)arg0;
		ToLua.Push(L, o);
		return 1;
	}
}

