//this source code was auto-generated by tolua#, do not modify it
using System;
using LuaInterface;

public class UnityEngine_Networking_ChannelQOSWrap
{
	public static void Register(LuaState L)
	{
		L.BeginClass(typeof(UnityEngine.Networking.ChannelQOS), typeof(System.Object));
		L.RegFunction("New", _CreateUnityEngine_Networking_ChannelQOS);
		L.RegFunction("__tostring", ToLua.op_ToString);
		L.RegVar("QOS", get_QOS, null);
		L.EndClass();
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int _CreateUnityEngine_Networking_ChannelQOS(IntPtr L)
	{
		try
		{
			int count = LuaDLL.lua_gettop(L);

			if (count == 0)
			{
				UnityEngine.Networking.ChannelQOS obj = new UnityEngine.Networking.ChannelQOS();
				ToLua.PushObject(L, obj);
				return 1;
			}
			else if (count == 1 && TypeChecker.CheckTypes(L, 1, typeof(UnityEngine.Networking.ChannelQOS)))
			{
				UnityEngine.Networking.ChannelQOS arg0 = (UnityEngine.Networking.ChannelQOS)ToLua.CheckObject(L, 1, typeof(UnityEngine.Networking.ChannelQOS));
				UnityEngine.Networking.ChannelQOS obj = new UnityEngine.Networking.ChannelQOS(arg0);
				ToLua.PushObject(L, obj);
				return 1;
			}
			else if (count == 1 && TypeChecker.CheckTypes(L, 1, typeof(UnityEngine.Networking.QosType)))
			{
				UnityEngine.Networking.QosType arg0 = (UnityEngine.Networking.QosType)ToLua.CheckObject(L, 1, typeof(UnityEngine.Networking.QosType));
				UnityEngine.Networking.ChannelQOS obj = new UnityEngine.Networking.ChannelQOS(arg0);
				ToLua.PushObject(L, obj);
				return 1;
			}
			else
			{
				return LuaDLL.luaL_throw(L, "invalid arguments to ctor method: UnityEngine.Networking.ChannelQOS.New");
			}
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_QOS(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			UnityEngine.Networking.ChannelQOS obj = (UnityEngine.Networking.ChannelQOS)o;
			UnityEngine.Networking.QosType ret = obj.QOS;
			ToLua.Push(L, ret);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o == null ? "attempt to index QOS on a nil value" : e.Message);
		}
	}
}

