//this source code was auto-generated by tolua#, do not modify it
using System;
using LuaInterface;

public class UnityEngine_ImageEffectTransformsToLDRWrap
{
	public static void Register(LuaState L)
	{
		L.BeginClass(typeof(UnityEngine.ImageEffectTransformsToLDR), typeof(System.Attribute));
		L.RegFunction("New", _CreateUnityEngine_ImageEffectTransformsToLDR);
		L.RegFunction("__tostring", ToLua.op_ToString);
		L.EndClass();
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int _CreateUnityEngine_ImageEffectTransformsToLDR(IntPtr L)
	{
		try
		{
			int count = LuaDLL.lua_gettop(L);

			if (count == 0)
			{
				UnityEngine.ImageEffectTransformsToLDR obj = new UnityEngine.ImageEffectTransformsToLDR();
				ToLua.PushObject(L, obj);
				return 1;
			}
			else
			{
				return LuaDLL.luaL_throw(L, "invalid arguments to ctor method: UnityEngine.ImageEffectTransformsToLDR.New");
			}
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}
}

