//this source code was auto-generated by tolua#, do not modify it
using System;
using LuaInterface;

public class UnityEngine_ParticleSystemCollisionModeWrap
{
	public static void Register(LuaState L)
	{
		L.BeginEnum(typeof(UnityEngine.ParticleSystemCollisionMode));
		L.RegVar("Collision3D", get_Collision3D, null);
		L.RegVar("Collision2D", get_Collision2D, null);
		L.RegFunction("IntToEnum", IntToEnum);
		L.EndEnum();
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_Collision3D(IntPtr L)
	{
		ToLua.Push(L, UnityEngine.ParticleSystemCollisionMode.Collision3D);
		return 1;
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_Collision2D(IntPtr L)
	{
		ToLua.Push(L, UnityEngine.ParticleSystemCollisionMode.Collision2D);
		return 1;
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int IntToEnum(IntPtr L)
	{
		int arg0 = (int)LuaDLL.lua_tonumber(L, 1);
		UnityEngine.ParticleSystemCollisionMode o = (UnityEngine.ParticleSystemCollisionMode)arg0;
		ToLua.Push(L, o);
		return 1;
	}
}

