//this source code was auto-generated by tolua#, do not modify it
using System;
using LuaInterface;

public class UnityEngine_ParticleSystemMeshShapeTypeWrap
{
	public static void Register(LuaState L)
	{
		L.BeginEnum(typeof(UnityEngine.ParticleSystemMeshShapeType));
		L.RegVar("Vertex", get_Vertex, null);
		L.RegVar("Edge", get_Edge, null);
		L.RegVar("Triangle", get_Triangle, null);
		L.RegFunction("IntToEnum", IntToEnum);
		L.EndEnum();
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_Vertex(IntPtr L)
	{
		ToLua.Push(L, UnityEngine.ParticleSystemMeshShapeType.Vertex);
		return 1;
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_Edge(IntPtr L)
	{
		ToLua.Push(L, UnityEngine.ParticleSystemMeshShapeType.Edge);
		return 1;
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_Triangle(IntPtr L)
	{
		ToLua.Push(L, UnityEngine.ParticleSystemMeshShapeType.Triangle);
		return 1;
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int IntToEnum(IntPtr L)
	{
		int arg0 = (int)LuaDLL.lua_tonumber(L, 1);
		UnityEngine.ParticleSystemMeshShapeType o = (UnityEngine.ParticleSystemMeshShapeType)arg0;
		ToLua.Push(L, o);
		return 1;
	}
}

