//this source code was auto-generated by tolua#, do not modify it
using System;
using LuaInterface;

public class UnityEngine_EventSystems_EventHandleWrap
{
	public static void Register(LuaState L)
	{
		L.BeginEnum(typeof(UnityEngine.EventSystems.EventHandle));
		L.RegVar("Unused", get_Unused, null);
		L.RegVar("Used", get_Used, null);
		L.RegFunction("IntToEnum", IntToEnum);
		L.EndEnum();
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_Unused(IntPtr L)
	{
		ToLua.Push(L, UnityEngine.EventSystems.EventHandle.Unused);
		return 1;
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_Used(IntPtr L)
	{
		ToLua.Push(L, UnityEngine.EventSystems.EventHandle.Used);
		return 1;
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int IntToEnum(IntPtr L)
	{
		int arg0 = (int)LuaDLL.lua_tonumber(L, 1);
		UnityEngine.EventSystems.EventHandle o = (UnityEngine.EventSystems.EventHandle)arg0;
		ToLua.Push(L, o);
		return 1;
	}
}

