//this source code was auto-generated by tolua#, do not modify it
using System;
using LuaInterface;

public class UnityEngine_ParticleSystemScalingModeWrap
{
	public static void Register(LuaState L)
	{
		L.BeginEnum(typeof(UnityEngine.ParticleSystemScalingMode));
		L.RegVar("Hierarchy", get_Hierarchy, null);
		L.RegVar("Local", get_Local, null);
		L.RegVar("Shape", get_Shape, null);
		L.RegFunction("IntToEnum", IntToEnum);
		L.EndEnum();
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_Hierarchy(IntPtr L)
	{
		ToLua.Push(L, UnityEngine.ParticleSystemScalingMode.Hierarchy);
		return 1;
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_Local(IntPtr L)
	{
		ToLua.Push(L, UnityEngine.ParticleSystemScalingMode.Local);
		return 1;
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_Shape(IntPtr L)
	{
		ToLua.Push(L, UnityEngine.ParticleSystemScalingMode.Shape);
		return 1;
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int IntToEnum(IntPtr L)
	{
		int arg0 = (int)LuaDLL.lua_tonumber(L, 1);
		UnityEngine.ParticleSystemScalingMode o = (UnityEngine.ParticleSystemScalingMode)arg0;
		ToLua.Push(L, o);
		return 1;
	}
}

