//this source code was auto-generated by tolua#, do not modify it
using System;
using LuaInterface;

public class UnityEngine_Rendering_BuiltinRenderTextureTypeWrap
{
	public static void Register(LuaState L)
	{
		L.BeginEnum(typeof(UnityEngine.Rendering.BuiltinRenderTextureType));
		L.RegVar("None", get_None, null);
		L.RegVar("CurrentActive", get_CurrentActive, null);
		L.RegVar("CameraTarget", get_CameraTarget, null);
		L.RegVar("Depth", get_Depth, null);
		L.RegVar("DepthNormals", get_DepthNormals, null);
		L.RegVar("PrepassNormalsSpec", get_PrepassNormalsSpec, null);
		L.RegVar("PrepassLight", get_PrepassLight, null);
		L.RegVar("PrepassLightSpec", get_PrepassLightSpec, null);
		L.RegVar("GBuffer0", get_GBuffer0, null);
		L.RegVar("GBuffer1", get_GBuffer1, null);
		L.RegVar("GBuffer2", get_GBuffer2, null);
		L.RegVar("GBuffer3", get_GBuffer3, null);
		L.RegVar("Reflections", get_Reflections, null);
		L.RegFunction("IntToEnum", IntToEnum);
		L.EndEnum();
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_None(IntPtr L)
	{
		ToLua.Push(L, UnityEngine.Rendering.BuiltinRenderTextureType.None);
		return 1;
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_CurrentActive(IntPtr L)
	{
		ToLua.Push(L, UnityEngine.Rendering.BuiltinRenderTextureType.CurrentActive);
		return 1;
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_CameraTarget(IntPtr L)
	{
		ToLua.Push(L, UnityEngine.Rendering.BuiltinRenderTextureType.CameraTarget);
		return 1;
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_Depth(IntPtr L)
	{
		ToLua.Push(L, UnityEngine.Rendering.BuiltinRenderTextureType.Depth);
		return 1;
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_DepthNormals(IntPtr L)
	{
		ToLua.Push(L, UnityEngine.Rendering.BuiltinRenderTextureType.DepthNormals);
		return 1;
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_PrepassNormalsSpec(IntPtr L)
	{
		ToLua.Push(L, UnityEngine.Rendering.BuiltinRenderTextureType.PrepassNormalsSpec);
		return 1;
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_PrepassLight(IntPtr L)
	{
		ToLua.Push(L, UnityEngine.Rendering.BuiltinRenderTextureType.PrepassLight);
		return 1;
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_PrepassLightSpec(IntPtr L)
	{
		ToLua.Push(L, UnityEngine.Rendering.BuiltinRenderTextureType.PrepassLightSpec);
		return 1;
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_GBuffer0(IntPtr L)
	{
		ToLua.Push(L, UnityEngine.Rendering.BuiltinRenderTextureType.GBuffer0);
		return 1;
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_GBuffer1(IntPtr L)
	{
		ToLua.Push(L, UnityEngine.Rendering.BuiltinRenderTextureType.GBuffer1);
		return 1;
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_GBuffer2(IntPtr L)
	{
		ToLua.Push(L, UnityEngine.Rendering.BuiltinRenderTextureType.GBuffer2);
		return 1;
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_GBuffer3(IntPtr L)
	{
		ToLua.Push(L, UnityEngine.Rendering.BuiltinRenderTextureType.GBuffer3);
		return 1;
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_Reflections(IntPtr L)
	{
		ToLua.Push(L, UnityEngine.Rendering.BuiltinRenderTextureType.Reflections);
		return 1;
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int IntToEnum(IntPtr L)
	{
		int arg0 = (int)LuaDLL.lua_tonumber(L, 1);
		UnityEngine.Rendering.BuiltinRenderTextureType o = (UnityEngine.Rendering.BuiltinRenderTextureType)arg0;
		ToLua.Push(L, o);
		return 1;
	}
}

