//this source code was auto-generated by tolua#, do not modify it
using System;
using LuaInterface;

public class UnityEngine_Events_UnityEvent_UnityEngine_EventSystems_BaseEventDataWrap
{
	public static void Register(LuaState L)
	{
		L.BeginClass(typeof(UnityEngine.Events.UnityEvent<UnityEngine.EventSystems.BaseEventData>), typeof(UnityEngine.Events.UnityEventBase), "UnityEvent_UnityEngine_EventSystems_BaseEventData");
		L.RegFunction("AddListener", AddListener);
		L.RegFunction("RemoveListener", RemoveListener);
		L.RegFunction("Invoke", Invoke);
		L.RegFunction("__tostring", ToLua.op_ToString);
		L.EndClass();
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int AddListener(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 2);
			UnityEngine.Events.UnityEvent<UnityEngine.EventSystems.BaseEventData> obj = (UnityEngine.Events.UnityEvent<UnityEngine.EventSystems.BaseEventData>)ToLua.CheckObject(L, 1, typeof(UnityEngine.Events.UnityEvent<UnityEngine.EventSystems.BaseEventData>));
			UnityEngine.Events.UnityAction<UnityEngine.EventSystems.BaseEventData> arg0 = null;
			LuaTypes funcType2 = LuaDLL.lua_type(L, 2);

			if (funcType2 != LuaTypes.LUA_TFUNCTION)
			{
				 arg0 = (UnityEngine.Events.UnityAction<UnityEngine.EventSystems.BaseEventData>)ToLua.CheckObject(L, 2, typeof(UnityEngine.Events.UnityAction<UnityEngine.EventSystems.BaseEventData>));
			}
			else
			{
				LuaFunction func = ToLua.ToLuaFunction(L, 2);
				arg0 = DelegateFactory.CreateDelegate(typeof(UnityEngine.Events.UnityAction<UnityEngine.EventSystems.BaseEventData>), func) as UnityEngine.Events.UnityAction<UnityEngine.EventSystems.BaseEventData>;
			}

			obj.AddListener(arg0);
			return 0;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int RemoveListener(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 2);
			UnityEngine.Events.UnityEvent<UnityEngine.EventSystems.BaseEventData> obj = (UnityEngine.Events.UnityEvent<UnityEngine.EventSystems.BaseEventData>)ToLua.CheckObject(L, 1, typeof(UnityEngine.Events.UnityEvent<UnityEngine.EventSystems.BaseEventData>));
			UnityEngine.Events.UnityAction<UnityEngine.EventSystems.BaseEventData> arg0 = null;
			LuaTypes funcType2 = LuaDLL.lua_type(L, 2);

			if (funcType2 != LuaTypes.LUA_TFUNCTION)
			{
				 arg0 = (UnityEngine.Events.UnityAction<UnityEngine.EventSystems.BaseEventData>)ToLua.CheckObject(L, 2, typeof(UnityEngine.Events.UnityAction<UnityEngine.EventSystems.BaseEventData>));
			}
			else
			{
				LuaFunction func = ToLua.ToLuaFunction(L, 2);
				arg0 = DelegateFactory.CreateDelegate(typeof(UnityEngine.Events.UnityAction<UnityEngine.EventSystems.BaseEventData>), func) as UnityEngine.Events.UnityAction<UnityEngine.EventSystems.BaseEventData>;
			}

			obj.RemoveListener(arg0);
			return 0;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int Invoke(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 2);
			UnityEngine.Events.UnityEvent<UnityEngine.EventSystems.BaseEventData> obj = (UnityEngine.Events.UnityEvent<UnityEngine.EventSystems.BaseEventData>)ToLua.CheckObject(L, 1, typeof(UnityEngine.Events.UnityEvent<UnityEngine.EventSystems.BaseEventData>));
			UnityEngine.EventSystems.BaseEventData arg0 = (UnityEngine.EventSystems.BaseEventData)ToLua.CheckObject(L, 2, typeof(UnityEngine.EventSystems.BaseEventData));
			obj.Invoke(arg0);
			return 0;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}
}

