//this source code was auto-generated by tolua#, do not modify it
using System;
using LuaInterface;

public class UnityEngine_NavMeshObstacleShapeWrap
{
	public static void Register(LuaState L)
	{
		L.BeginEnum(typeof(UnityEngine.NavMeshObstacleShape));
		L.RegVar("Capsule", get_Capsule, null);
		L.RegVar("Box", get_Box, null);
		L.RegFunction("IntToEnum", IntToEnum);
		L.EndEnum();
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_Capsule(IntPtr L)
	{
		ToLua.Push(L, UnityEngine.NavMeshObstacleShape.Capsule);
		return 1;
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_Box(IntPtr L)
	{
		ToLua.Push(L, UnityEngine.NavMeshObstacleShape.Box);
		return 1;
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int IntToEnum(IntPtr L)
	{
		int arg0 = (int)LuaDLL.lua_tonumber(L, 1);
		UnityEngine.NavMeshObstacleShape o = (UnityEngine.NavMeshObstacleShape)arg0;
		ToLua.Push(L, o);
		return 1;
	}
}

