//this source code was auto-generated by tolua#, do not modify it
using System;
using LuaInterface;

public class UnityEngine_GUI_ScrollViewScopeWrap
{
	public static void Register(LuaState L)
	{
		L.BeginClass(typeof(UnityEngine.GUI.ScrollViewScope), typeof(UnityEngine.GUI.Scope));
		L.RegFunction("New", _CreateUnityEngine_GUI_ScrollViewScope);
		L.RegFunction("__tostring", ToLua.op_ToString);
		L.RegVar("scrollPosition", get_scrollPosition, null);
		L.RegVar("handleScrollWheel", get_handleScrollWheel, set_handleScrollWheel);
		L.EndClass();
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int _CreateUnityEngine_GUI_ScrollViewScope(IntPtr L)
	{
		try
		{
			int count = LuaDLL.lua_gettop(L);

			if (count == 3)
			{
				UnityEngine.Rect arg0 = (UnityEngine.Rect)ToLua.CheckObject(L, 1, typeof(UnityEngine.Rect));
				UnityEngine.Vector2 arg1 = ToLua.ToVector2(L, 2);
				UnityEngine.Rect arg2 = (UnityEngine.Rect)ToLua.CheckObject(L, 3, typeof(UnityEngine.Rect));
				UnityEngine.GUI.ScrollViewScope obj = new UnityEngine.GUI.ScrollViewScope(arg0, arg1, arg2);
				ToLua.PushObject(L, obj);
				return 1;
			}
			else if (count == 5 && TypeChecker.CheckTypes(L, 1, typeof(UnityEngine.Rect), typeof(UnityEngine.Vector2), typeof(UnityEngine.Rect), typeof(UnityEngine.GUIStyle), typeof(UnityEngine.GUIStyle)))
			{
				UnityEngine.Rect arg0 = (UnityEngine.Rect)ToLua.CheckObject(L, 1, typeof(UnityEngine.Rect));
				UnityEngine.Vector2 arg1 = ToLua.ToVector2(L, 2);
				UnityEngine.Rect arg2 = (UnityEngine.Rect)ToLua.CheckObject(L, 3, typeof(UnityEngine.Rect));
				UnityEngine.GUIStyle arg3 = (UnityEngine.GUIStyle)ToLua.CheckObject(L, 4, typeof(UnityEngine.GUIStyle));
				UnityEngine.GUIStyle arg4 = (UnityEngine.GUIStyle)ToLua.CheckObject(L, 5, typeof(UnityEngine.GUIStyle));
				UnityEngine.GUI.ScrollViewScope obj = new UnityEngine.GUI.ScrollViewScope(arg0, arg1, arg2, arg3, arg4);
				ToLua.PushObject(L, obj);
				return 1;
			}
			else if (count == 5 && TypeChecker.CheckTypes(L, 1, typeof(UnityEngine.Rect), typeof(UnityEngine.Vector2), typeof(UnityEngine.Rect), typeof(bool), typeof(bool)))
			{
				UnityEngine.Rect arg0 = (UnityEngine.Rect)ToLua.CheckObject(L, 1, typeof(UnityEngine.Rect));
				UnityEngine.Vector2 arg1 = ToLua.ToVector2(L, 2);
				UnityEngine.Rect arg2 = (UnityEngine.Rect)ToLua.CheckObject(L, 3, typeof(UnityEngine.Rect));
				bool arg3 = LuaDLL.luaL_checkboolean(L, 4);
				bool arg4 = LuaDLL.luaL_checkboolean(L, 5);
				UnityEngine.GUI.ScrollViewScope obj = new UnityEngine.GUI.ScrollViewScope(arg0, arg1, arg2, arg3, arg4);
				ToLua.PushObject(L, obj);
				return 1;
			}
			else if (count == 7 && TypeChecker.CheckTypes(L, 1, typeof(UnityEngine.Rect), typeof(UnityEngine.Vector2), typeof(UnityEngine.Rect), typeof(bool), typeof(bool), typeof(UnityEngine.GUIStyle), typeof(UnityEngine.GUIStyle)))
			{
				UnityEngine.Rect arg0 = (UnityEngine.Rect)ToLua.CheckObject(L, 1, typeof(UnityEngine.Rect));
				UnityEngine.Vector2 arg1 = ToLua.ToVector2(L, 2);
				UnityEngine.Rect arg2 = (UnityEngine.Rect)ToLua.CheckObject(L, 3, typeof(UnityEngine.Rect));
				bool arg3 = LuaDLL.luaL_checkboolean(L, 4);
				bool arg4 = LuaDLL.luaL_checkboolean(L, 5);
				UnityEngine.GUIStyle arg5 = (UnityEngine.GUIStyle)ToLua.CheckObject(L, 6, typeof(UnityEngine.GUIStyle));
				UnityEngine.GUIStyle arg6 = (UnityEngine.GUIStyle)ToLua.CheckObject(L, 7, typeof(UnityEngine.GUIStyle));
				UnityEngine.GUI.ScrollViewScope obj = new UnityEngine.GUI.ScrollViewScope(arg0, arg1, arg2, arg3, arg4, arg5, arg6);
				ToLua.PushObject(L, obj);
				return 1;
			}
			else
			{
				return LuaDLL.luaL_throw(L, "invalid arguments to ctor method: UnityEngine.GUI.ScrollViewScope.New");
			}
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_scrollPosition(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			UnityEngine.GUI.ScrollViewScope obj = (UnityEngine.GUI.ScrollViewScope)o;
			UnityEngine.Vector2 ret = obj.scrollPosition;
			ToLua.Push(L, ret);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o == null ? "attempt to index scrollPosition on a nil value" : e.Message);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_handleScrollWheel(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			UnityEngine.GUI.ScrollViewScope obj = (UnityEngine.GUI.ScrollViewScope)o;
			bool ret = obj.handleScrollWheel;
			LuaDLL.lua_pushboolean(L, ret);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o == null ? "attempt to index handleScrollWheel on a nil value" : e.Message);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int set_handleScrollWheel(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			UnityEngine.GUI.ScrollViewScope obj = (UnityEngine.GUI.ScrollViewScope)o;
			bool arg0 = LuaDLL.luaL_checkboolean(L, 2);
			obj.handleScrollWheel = arg0;
			return 0;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o == null ? "attempt to index handleScrollWheel on a nil value" : e.Message);
		}
	}
}

